---
title: "data import"
output: github_document
---

```{r}
library(tidyverse)
library(readxl)
library(haven)
```

let's import a dataset.

```{r}
litters_df=
  read_csv("FAS_litters.csv")
```

Look at your data!!
```{r}
names(litters_df)
```

Updates the names in `litters_df`.

```{r}
litters_df = 
  janitor::clean_names(litters_df)
```

Look at the data!!
```{r}
litters_df
```

Sometimes skimming data is neat?

```{r}
skimr::skim(litters_df)
```


## Fix the missigness

```{r}
litters_df = 
  read_csv("FAS_litters.csv", na = c("NA", ".", ""))
```

#import `FAS_pups.csv` and skip the first 3 lines

```{r}
pups_df=
  read_csv(
    "FAS_pups.csv",
    skip = 3, 
    na = c("NA", ".", "")
  )   

pups_df=
  janitor::clean_names(pups_df)
```

##Okay what about excel

CSVs are really great but sometimes you get an excel file. 

```{r}
mlb_df=
  read_excel("mlb11.xlsx")
```

Import LotR word counts.

```{r}
fotr_df=
  read_excel("LotR_Words.xlsx", range = "B3:D6")
```


## SAS???

Import the PULSE data

```{r}
pulse_df=
  read_sas("public_pulse_data.sas7bdat")

pulse_df=
  janitor::clean_names(pulse_df)
```


## Why do I hate read.csv so much??

```{r, eval = FALSE}
litters_df_base = 
  read.csv("FAS_litters.csv")
```

































